spring:
  application:
    name: order-service
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/choreostoreorderdb
    username: root
    password: Test$_$123

---

server:
  port: 8081

---

logging:
  level:
    com.sample.order: debug

---

topic:
  order-create: order-created-topic
  order-done: order-done-topic
  order-cancel: order-cancelled-topic

group:
  order-done: order-done-group
  order-cancel: order-cancelled-group
